### ISSUE TITLE
Remove dimmest color option that turns pure white.

### ISSUE THREAD

**Issue by shwaydogg** [climateclock/cclock#13]
The goal is to not allow the screen to appear that it's in a "Black and White" mode which could concern or distract user.

Either: 
A. Find the option brightness setting that still has at least some color in both red and blue and don't let the brightness setting drop below that.

B. Check if the color is pure white if so override the color and instead set the color to only turn on the blue or red pixel, respectively, as dim as possible of course. (Override both lifeline and deadline color if it occurs for either one.)

**Comment by zestyping** [comment]
1 point

**Comment by zestyping** [comment]
Option A doesn't work because then the allowable brightness setting would depend on what colours are present on the screen, which depends on which pixels are on the screen — thus drawing individual pixels could change the brightness setting of the whole screen.

Option B won't look good because the colour will suddenly go from desaturated to 100% saturated, and non-primary colours (such as yellow or purple) will suddenly change colour (yellow becomes green or red, purple becomes red or blue).

Solution:
- Compute the average colour value, (r + g + b)/3.
- Scale the brightness of each component as follows:
    - If the component is zero, always scale it to zero.
    - If the component is equal to or below the average, scale it down to at least 1 ulp (unit of least precision).
    - If the component is higher than the average, scale it down to at least 2 ulp (units of least precision).

This prevents any component from going to zero, while also preventing non-white colours from going to white.
